// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.DataAccessLayer.Data;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250519142519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.DataAccessLayer.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "En bankapplication byggd med ASP.NET Core Razor Pages med komplett användar-, kund- och kontohantering. Inkluderar transaktionshantering och säkerhetsfunktioner.",
                            GithubUrl = "https://github.com/yourusername/BankApp",
                            ImageUrl = "/images/projects/bank-system.jpg",
                            Name = "BankQ System",
                            ProjectUrl = "https://bankappazure20100723-hycsfhbadvc5b3fv.swedencentral-01.azurewebsites.net/",
                            TechStack = "ASP.NET Core 9, Razor Pages, Entity Framework Core, SQL Server, Bootstrap 5, Mapster"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ett REST API för annonshantering med CRUD-operationer. API:et tillåter sökning, filtrering och sortering av annonser.",
                            GithubUrl = "https://github.com/yourusername/AdsAPI",
                            ImageUrl = "/images/projects/ads-api.jpg",
                            Name = "Annons API",
                            ProjectUrl = "",
                            TechStack = "ASP.NET Core 9, Web API, Entity Framework Core, SQL Server, Swagger/OpenAPI"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
