// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.DataAccessLayer.Data;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250528153641_UpdateSiliconProjectDescription")]
    partial class UpdateSiliconProjectDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.DataAccessLayer.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A banking application built with ASP.NET Core Razor Pages with complete user, customer, and account management. Includes transaction handling and security features.",
                            GithubUrl = "https://github.com/eleonorareinaalminson/BankApp1",
                            ImageUrl = "/images/projects/bank-system.jpg",
                            Name = "BankQ System",
                            ProjectUrl = "https://bankappazure20100723-hycsfhbadvc5b3fv.swedencentral-01.azurewebsites.net/",
                            TechStack = "ASP.NET Core 9, Razor Pages, Entity Framework Core, SQL Server, Bootstrap 5, Mapster"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A RESTful API for ad management with CRUD operations. The API allows searching, filtering, and sorting of ads.",
                            GithubUrl = "https://github.com/eleonorareinaalminson/AdsAPI",
                            ImageUrl = "/images/projects/ads-api.jpg",
                            Name = "RESTful API",
                            ProjectUrl = "",
                            TechStack = "ASP.NET Core 9, Web API, Entity Framework Core, SQL Server, Swagger/OpenAPI"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A comprehensive banking application showcasing modern React development. Features include dark/light theme switching, responsive design across all devices, secure money transfer functionality, international payment processing, and dynamic FAQ system. Integrates with external APIs for testimonials and newsletter subscription. Built with React 19, Vite, and modern CSS practices including CSS Grid and Flexbox for optimal performance and user experience.",
                            GithubUrl = "https://github.com/eleonorareinaalminson/silicon-react",
                            ImageUrl = "/images/projects/silicon-react.jpg",
                            Name = "Silicon Banking App",
                            ProjectUrl = "",
                            TechStack = "React 19, Vite 6, React Router 7, CSS3 Variables, Bootstrap Icons, API Integration, Responsive Grid"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
