// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.DataAccessLayer.Data;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250519204259_UpdatedProjectDescriptionNew")]
    partial class UpdatedProjectDescriptionNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.DataAccessLayer.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A banking application built with ASP.NET Core Razor Pages with complete user, customer, and account management. Includes transaction handling and security features.",
                            GithubUrl = "https://github.com/eleonorareinaalminson/BankApp1",
                            ImageUrl = "/images/projects/bank-system.jpg",
                            Name = "BankQ System",
                            ProjectUrl = "https://bankappazure20100723-hycsfhbadvc5b3fv.swedencentral-01.azurewebsites.net/",
                            TechStack = "ASP.NET Core 9, Razor Pages, Entity Framework Core, SQL Server, Bootstrap 5, Mapster"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A RESTful API for ad management with CRUD operations. The API allows searching, filtering, and sorting of ads.",
                            GithubUrl = "https://github.com/eleonorareinaalminson/AdsAPI",
                            ImageUrl = "/images/projects/ads-api.jpg",
                            Name = "RESTful API",
                            ProjectUrl = "",
                            TechStack = "ASP.NET Core 9, Web API, Entity Framework Core, SQL Server, Swagger/OpenAPI"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A modern applikation built with React.",
                            GithubUrl = "https://github.com/eleonorareinaalminson/silicon-react",
                            ImageUrl = "/images/projects/silicon-react.jpg",
                            Name = "Silicon React App",
                            ProjectUrl = "",
                            TechStack = "React 19, React Router 7, CSS, Bootstrap Icons, Responsive Design"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
